name: Hello World Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Echo the content of hello_world.txt
      run: cat hello_world.txt
